export const GWR_EXTENSION_GM_XHR_REQUEST = 'GWR_EXTENSION_GM_XHR_REQUEST';
export const GWR_EXTENSION_GM_XHR_RESPONSE = 'GWR_EXTENSION_GM_XHR_RESPONSE';
export const GWR_EXTENSION_STATE_REQUEST = 'GWR_EXTENSION_STATE_REQUEST';
export const GWR_EXTENSION_STATE_RESPONSE = 'GWR_EXTENSION_STATE_RESPONSE';
